.PHONY: all clean clobber build-agda run-agda test-agda clean-agda clobber-agda build-rust run-rust clean-rust clobber-rust

all: test-agda

clean: clean-agda clean-rust

clobber: clobber-agda clobber-rust


# Agda-related targets

build-agda: agda-build/Main
agda-build/Main: agda/Main.agda
	mkdir -p agda-build
	agda \
	  --compile \
	  --library standard-library \
	  --include-path agda \
	  --compile-dir=agda-build \
		$<

run-agda: agda-build/Main
	./agda-build/Main

generated.rs: agda-build/Main
	./agda-build/Main > $@

expected.rs: rust/main.rs strip-comments.sh
	./strip-comments.sh rust/main.rs $@

test-agda: generated.rs expected.rs
	@echo "Comparing Agda-generated Rust code against expected output..."
	diff -u expected.rs generated.rs
	@echo "Output matches expected output."

# Delete all intermediate files, including the executable
clean-agda:
	rm -rf agda/*.agdai
	rm -rf agda-build

# Delete all generated files, including the Rust code generated by running the Agda program
clobber-agda: clean-agda
	rm -f generated.rs expected.rs


# Rust related targets

build-rust: rust/main.rs
	mkdir -p rust-build
	cargo build

run-rust: rust/main.rs
	cargo run

# Delete all intermediate files, including the executable
clean-rust:
	cargo clean

clobber-rust: clean-rust
